name: "Validate Branch Naming Convention"

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          branch_name="${{ github.ref_name }}"
          
          # Define the regex pattern for branch names
          if [[ ! "$branch_name" =~ ^feature/[a-zA-Z0-9_-]+-[0-9]+$ ]]; then
            echo "Branch name \"$branch_name\" does not follow the required convention: feature/<branch-name>-<story-id>"
            exit 1
          else
            echo "Branch name \"$branch_name\" follows the naming convention."
          fi
