name: Python Dependency Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Adjust to your Python version

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Run the application (optional, if you want to ensure it works)
    - name: Run application (optional)
      run: |
        python app.py  # Modify this if your entry point is different

    # Dependency check
    - name: Check for failed dependencies
      run: |
        pip check  # This checks for broken dependencies
