name: OWASP Dependency-Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dependency-check:
    name: OWASP Dependency-Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java environment (if your project uses Java)
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: OWASP Dependency-Check
        run: |
          docker run --rm \
            --volume $(pwd):/src \
            --volume $(pwd)/odc-data:/usr/share/dependency-check/data \
            --volume $(pwd)/odc-reports:/report \
            owasp/dependency-check \
            --scan /src \
            --format "ALL" \
            --out /report \
            --project "python"

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: ./odc-reports
