name: OWASP Dependency-Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  dependency_check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java (OWASP Dependency-Check requires Java)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'  # Dependency-Check requires Java

      # Step 3: Download and unzip OWASP Dependency-Check
      - name: Install OWASP Dependency-Check
        run: |
          # Download OWASP Dependency-Check
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.2.1/dependency-check-8.2.1-release.zip

          # Create directory for extraction
          mkdir dependency-check

          # Unzip Dependency-Check
          unzip dependency-check-8.2.1-release.zip -d dependency-check

          # Step 4: List the contents to find the exact path
          ls -la dependency-check

          # Assuming the correct path is found, update permission for the script
          chmod +x dependency-check/bin/dependency-check.sh

      # Step 5: Run OWASP Dependency-Check scan
      - name: Run OWASP Dependency-Check
        run: |
          dependency-check/bin/dependency-check.sh \
          --project "MyProject" \
          --scan ${{ github.workspace }} \
          --format "HTML" \
          --out ${{ github.workspace }}/dependency-check-report

      # Step 6: Upload the report as an artifact
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: ${{ github.workspace }}/dependency-check-report/
