name: Python Security Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  safety:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install safety

      - name: Run Safety Check and output to file
        run: safety check -r requirements.txt --output text > safety_report.txt

      - name: Upload Safety report artifact
        uses: actions/upload-artifact@v3
        with:
          name: safety-report
          path: safety_report.txt
